src/portal/portal/urls.py
from django.contrib import admin
from django.urls import include, path


urlpatterns = [
    path('', include('puffer.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

src/portal/puffer/urls.py
from django.urls import path, re_path
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('favicon.ico/', RedirectView.as_view(
         url=staticfiles_storage.url('puffer/dist/images/favicon.ico')),
         name='favicon'),
    path('player/', views.player, name='player'),
    path('faq/', views.faq, name='faq'),
    path('terms/', views.terms, name='terms'),
    path('results/', views.results, name='results'),
    re_path(r'^results/(?P<input_date>[0-9]{4}-[0-9]{2}-[0-9]{2})/$',
            views.results, name='results'),
    path('data-description/', views.data_description, name='data-description'),
    path('bola/', views.bola, name='bola'),
    path('error_reporting/', views.error_reporting, name='error_reporting'),
]

src/portal/accounts/models.py
from django.db import models
from django.contrib.auth.models import User


class InvitationToken(models.Model):
    token = models.CharField(max_length=64, unique=True)
    holder = models.ForeignKey(User, on_delete=models.CASCADE,
                               null=True, blank=True)
    # when a user registers an account with this token, the new account will
    # be assigned and hold "addon_cnt" extra tokens for distribution
    addon_cnt = models.PositiveIntegerField(default=0)
    shared = models.BooleanField(default=False)

    def __str__(self):
        holder = self.holder.username if self.holder else 'unassigned'
        return '%s (%s, %d): shared=%s' % (self.token, holder, self.addon_cnt,
                                           self.shared)

src/portal/puffer/models.py
from django.db import models
from django.contrib.sessions.models import Session
from django.contrib.auth.models import User
from django.contrib.auth.signals import user_logged_in
from django.core.validators import MaxValueValidator, MinValueValidator


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE,
                                primary_key=True)
    last_session_key = models.CharField(max_length=64, default='')


class GrafanaSnapshot(models.Model):
    url = models.URLField()
    created_on = models.DateTimeField()


class Rating(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500, default='')
    stars = models.IntegerField(
        validators=[MinValueValidator(0), MaxValueValidator(5)], default=0)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return '{}-{}-{}'.format(self.user, self.stars, self.comment_text)


class Participate(models.Model):
    email = models.CharField(max_length=255)
    request_date = models.DateTimeField('date requested')
    sent = models.BooleanField(default=False)

    def __str__(self):
        return self.email

# classes above are not currrently used

def user_logged_in_handler(sender, request, user, **kwargs):
    curr_session_key = request.session.session_key

    if not curr_session_key:
        request.session.create()
        curr_session_key = request.session.session_key
        return

    user_profile, _ = UserProfile.objects.get_or_create(user=user)
    last_session_key = user_profile.last_session_key

    # user does not have a profile or a session key previously
    if not last_session_key:
        user_profile.last_session_key = curr_session_key
        user_profile.save()
        return

    # do nothing if user's session key does not change
    if curr_session_key == last_session_key:
        return

    # delete previous session and set the new session key
    try:
        user_session = Session.objects.get(session_key=last_session_key)
    except Session.DoesNotExist:
        user_session = None

    if user_session:
        user_session.delete()

    user_profile.last_session_key = curr_session_key
    user_profile.save()


user_logged_in.connect(user_logged_in_handler)

src/portal/puffer/views.py
import os
import json
import random
from datetime import datetime
from influxdb import InfluxDBClient

from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.core.validators import validate_email
from django.core.exceptions import ValidationError
from django.conf import settings
from django.http import HttpResponse
from accounts.models import InvitationToken
from accounts.utils import random_token

from .models import Rating, GrafanaSnapshot, Participate


def index(request):
    return render(request, 'puffer/index.html')


def faq(request):
    return render(request, 'puffer/faq.html')


def terms(request):
    return render(request, 'puffer/terms.html')


def data_description(request):
    return render(request, 'puffer/data-description.html')

def bola(request):
    return render(request, 'puffer/bola.html')


def results(request, input_date=''):
    context = {'input_date': input_date}
    return render(request, 'puffer/results.html', context)


@login_required(login_url='/accounts/login/')
def player(request):
    # generate a random port or use a superuser-specified port
    port = None
    if request.user.is_superuser:
        port = request.GET.get('port', None)

    if port is None:
        total_servers = settings.TOTAL_SERVERS
        base_port = settings.WS_BASE_PORT
        port = str(base_port + random.randint(1, total_servers))

    # parameters passed to Javascript stored in JSON
    params = {'session_key': request.session.session_key,
              'username': request.user.username,
              'debug': settings.DEBUG,
              'port': port}
    context = {'params_json': json.dumps(params)}

    return render(request, 'puffer/player.html', context)


@login_required(login_url='/accounts/login/')
def error_reporting(request):
    if request.method == 'POST':
        influx = settings.INFLUXDB
        # ignore reported error if no InfluxDB has been set up
        if influx is None:
            return HttpResponse(status=204)  # No Content

        error_json = json.loads(request.body.decode())

        json_body = [{
            'time': datetime.utcnow().strftime('%Y-%m-%dT%H:%M:%S.%fZ'),
            'measurement': 'client_error',
            'tags': {},
            'fields': {'user': error_json['username'],
                       'init_id': error_json['init_id'],
                       'error': error_json['error']}
        }]

        client = InfluxDBClient(
            influx['host'], influx['port'], influx['user'],
            os.environ[influx['password']], influx['dbname'])
        client.write_points(json_body, time_precision='ms')

        return HttpResponse(status=204)  # No Content
    else:
        return HttpResponse(status=405)  # Method Not Allowed


# functions below are not currently used

@login_required(login_url='/accounts/login/')
def monitoring(request):
    snapshot = GrafanaSnapshot.objects.order_by('-created_on').first()

    if not snapshot:
        return render(request, 'puffer/404.html')

    # only display a snapshot newer than 1 hour ago
    time_diff = datetime.utcnow() - snapshot.created_on
    if time_diff.total_seconds() > 3600:
        return render(request, 'puffer/404.html')

    context = {'snapshot_url': snapshot.url}
    return render(request, 'puffer/monitoring.html', context)


@login_required(login_url='/accounts/login/')
def profile(request):
    if request.method != 'POST':
        return render(request, 'puffer/profile.html')

    if request.user.is_superuser:
        addon_cnt = int(request.POST.get('addon-cnt'))

        InvitationToken.objects.create(
            token=random_token(), holder=request.user, addon_cnt=addon_cnt)

    return render(request, 'puffer/profile.html')


@login_required(login_url='/accounts/login/')
def rating(request):
    if request.method != 'POST':
        context = {'star_pattern': ['x' * i for i in range(1, 6)]}
        return render(request, 'puffer/rating.html', context)

    new_star = 0
    new_comment = request.POST['rating-comment']
    if 'rating-star' in request.POST:
        new_star = request.POST['rating-star']

    if new_star == 0 and new_comment == '':
        messages.info(request, 'Please tell us about our service.')
        return redirect('rating')

    try:
        Rating.objects.create(user=request.user, comment_text=new_comment,
                              stars=new_star, pub_date=datetime.utcnow())
        messages.success(request, 'Thank you for rating us!')
        return redirect('player')
    except:
        messages.error(request, 'Internal error: Please try again.')
        return redirect('rating')


def participate(request):
    if request.method != 'POST':
        return render(request, 'puffer/participate.html')

    email = request.POST['email-field']

    try:
        validate_email(email)
    except ValidationError:
        messages.error(request, 'Please provide a valid email.')
        return redirect('participate')

    try:
        Participate.objects.create(email=email, request_date=datetime.utcnow())
        messages.success(request,
            'Thank you for requesting to participate! We will contact you with'
            ' an invitation code when room becomes available.')
        return redirect('participate')
    except:
        messages.error(request, 'Internal error: Please try again.')
        return redirect('participate')

src/portal/puffer/templates/puffer/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117951942-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-117951942-2');
    gtag('config', 'AW-771906819');
  </script>
  <link rel="stylesheet" href="{% static 'puffer/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'puffer/css/common.css' %}">
  <title>Puffer</title>
  <link rel="icon" href="{% static 'puffer/dist/images/favicon.ico' %}">
</head>

<body>
  <!-- Navigation -->
  {% include "puffer/navigation.html" %}

  <!-- Jumbotron -->
  <div class="jumbotron">
    <div class="container">

      <div class="text-center">
        <img class="mb-4" src="{% static 'puffer/dist/images/logo-full.svg' %}"
             alt="Puffer" height="160px">
      </div>

      <div class="row justify-content-md-center">
        <div class="col-md-6 text-justify">

        <p>Stream live TV in your browser. There's no charge.
           You can watch U.S. TV stations affiliated with the
           NBC, CBS, ABC, PBS, Fox, and CW networks.</p>

        <p>Puffer works well in the Chrome, Firefox, Edge, and Opera browsers,
           on a computer or an Android phone or tablet.
           Puffer <b>does not</b> work on iPhones or iPads or in the Safari browser.</p>

        <p>Puffer is a research project in the computer-science department at Stanford University.
           Please see the <a href="{% url 'faq' %}">FAQ</a> and our
           <a href="https://www.usenix.org/conference/nsdi20/presentation/yan">research paper</a>
           (<em>Community Award</em> winner at USENIX NSDI 2020) for more information.</p>
        </div>
      </div>

      <div class="text-center">
        {% if user.is_authenticated %}
        <a role="button" class="btn btn-primary btn-lg" href="{% url 'player' %}">Watch TV</a>
        {% else %}
        <a role="button" class="btn btn-primary" href="{% url 'signup' %}">Sign up</a>
        <a role="button" class="btn btn-outline-primary" href="{% url 'player' %}">Log in</a>
        {% endif %}
      </div>

    </div>
  </div>

  <footer class="footer font-small pb-3">
    <div class="container">
      <div class="row text-center d-flex justify-content-center">
        <div class="col-md-2">
          <a href="{% url 'terms' %}">Terms of Participation</a>
        </div>

        <div class="col-md-2">
          <a href="https://groups.google.com/forum/#!forum/puffer-stanford">Contact</a>
        </div>

        <div class="col-md-2">
          <a href="mailto:puffer-copyright-notices@cs.stanford.edu">Copyright complaints</a>
        </div>
      </div>
    </div>
  </footer>

  <script src="{% static 'puffer/dist/js/jquery-3.3.1.slim.min.js' %}"></script>
  <script src="{% static 'puffer/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

src/portal/puffer/templates/puffer/monitoring.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117951942-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-117951942-2');
    gtag('config', 'AW-771906819');
  </script>
  <link rel="stylesheet" href="{% static 'puffer/css/common.css' %}">
  <title>Puffer</title>
  <link rel="icon" href="{% static 'puffer/dist/images/favicon.ico' %}">
</head>

<body class="m-0">
  <iframe class="fullscreen" src="{{ snapshot_url }}">
    <p>
      Your browser does not support iframe, which Puffer requires to display Grafana snapshots
      without redirecting. Please <a href="{{ snapshot_url }}">click here</a> instead.
    </p>
  </iframe>
</body>

</html>

src/portal/puffer/templates/puffer/navigation.html
{% load static %}

<nav class="navbar navbar-expand-md navbar-light border-bottom py-3">
  <div class="container d-flex">
    <a class="navbar-brand" href="{% url 'index' %}">
      <img src="{% static 'puffer/dist/images/logo-text.svg' %}"
           alt="Puffer" height="25px">
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar-main"
            aria-controls="navbar-main" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbar-main">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'player' %}">Watch TV</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'faq' %}">About Puffer</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="https://github.com/StanfordSNR/puffer">Source Code</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="dropdownMenuLink"
             data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Research Study</a>
          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
            <a class="dropdown-item" href="{% static 'puffer/documents/puffer-paper.pdf' %}">Research Paper</a>
            <a class="dropdown-item" href="https://youtu.be/63aECX2MZvY">Conference Talk</a>
            <a class="dropdown-item" href="{% url 'results' %}">Experiment Results</a>
            <a class="dropdown-item" href="{% url 'data-description' %}">Data Description</a>
            <a class="dropdown-item" href="{% url 'bola' %}">BOLA</a>
          </div>
        </li>
      </ul>
    </div>

    <div class="ml-auto">
      {% if user.is_authenticated %}
      <a role="button" class="btn btn-link" href="{% url 'logout' %}">Sign out</a>
      <span style="vertical-align:middle;">{{ user.username }}</span>
      {% else %}
      <a role="button" class="btn btn-primary" href="{% url 'signup' %}">Sign up</a>
      <a role="button" class="btn btn-outline-primary" href="{% url 'player' %}">Log in</a>
      {% endif %}
      </ul>
    </div>
  </div>
</nav>

src/portal/puffer/templates/puffer/participate.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'puffer/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'puffer/css/common.css' %}">
  <title>Puffer</title>
  <link rel="icon" href="{% static 'puffer/dist/images/favicon.ico' %}">
</head>

<body>
  <!-- Navigation -->
  {% include "puffer/navigation.html" %}

  <!-- Participate Form -->
  <div class="container py-4">
    <!-- Success or error messages -->
    {% if messages %}
    <ul class="list-unstyled">
    {% for msg in messages %}
      <li>
        <div class="alert alert-{{msg.level_tag}}" role="alert">
          {{msg.message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </li>
    {% endfor %}
    </ul>
    {% endif %}

    <h3 class="font-weight-normal mt-3">Sign Up to Watch Puffer</h3>
    <br>

    <p>
      Puffer is a research project run by the Stanford Systems and Networking Research Group.
      The goal of this project is to investigate methods for improving live streaming of video
      over the Internet. To that end, we provide live rebroadcasts over the Internet of broadcast
      television channels available over-the-air in the Bay Area.
      To learn more about Puffer, please visit our <a href="{% url 'faq' %}">FAQ.</a>
    </p>
    <p>
      To avoid overwhelming our infrastructure, we are slowing growing the number of users on
      Puffer, with an eventual goal of 500 simultaneous viewers. As such, signing up for Puffer
      requires an invitation token. To request an invitation token from the Puffer team, please
      enter your email below, and we will provide you with one as soon as we can.
      We will never share your email with anyone else.
    </p>

    <p><form class="form-inline" method="post" action="{% url 'participate' %}">
      {% csrf_token %}

      <div class="form-group">
        <input type="text" class="form-control mr-3" name="email-field" id="email-field"
               placeholder="Please enter your email" style="width:300px" required></input>
      </div>
      <button type="submit" class="btn btn-primary">Request a token</button>
    </form></p>

    <p>Already have an invitation token? <a href="{% url 'signup' %}">Sign up here.</a></p>
  </div>

  <script src="{% static 'puffer/dist/js/jquery-3.3.1.slim.min.js' %}"></script>
  <script src="{% static 'puffer/dist/js/bootstrap.bundle.min.js' %}"></script>
</body>

</html>

src/portal/puffer/templates/puffer/player.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <!-- Global site tag (gtag.js) - Google Analytics -->
  <script async src="https://www.googletagmanager.com/gtag/js?id=UA-117951942-2"></script>
  <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-117951942-2');
    gtag('config', 'AW-771906819');
  </script>
  <link rel="stylesheet" href="{% static 'puffer/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'puffer/css/common.css' %}">
  <link rel="stylesheet" href="{% static 'puffer/css/player.css' %}">
  <title>Puffer</title>
  <link rel="icon" href="{% static 'puffer/dist/images/favicon.ico' %}">

  <!-- Reddit Conversion Pixel -->
  <script>
  !function(w,d){if(!w.rdt){var p=w.rdt=function(){p.sendEvent?p.sendEvent.apply(p,arguments):p.callQueue.push(arguments)};p.callQueue=[];var t=d.createElement("script");t.src="https://www.redditstatic.com/ads/pixel.js",t.async=!0;var s=d.getElementsByTagName("script")[0];s.parentNode.insertBefore(t,s)}}(window,document);rdt('init','t2_3vk4c');rdt('track', 'PageVisit');
  </script>
  <!-- DO NOT MODIFY -->
  <!-- End Reddit Conversion Pixel -->
</head>

<body>
  <!-- Navigation -->
  {% include "puffer/navigation.html" %}

  <!-- Player -->
  <div class="container py-4">
    <!-- Success or error messages -->
    {% if messages %}
    <ul class="list-unstyled">
    {% for msg in messages %}
      <li>
        <div class="alert alert-{{msg.level_tag}}" role="alert">
          {{msg.message}}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </li>
    {% endfor %}
    </ul>
    {% endif %}

    <div class="row">
      <div class="col-md-9 mt-3">
        <ul class="list-unstyled" id="player-error-list"></ul>

        <div class="embed-responsive embed-responsive-16by9">
          <div id="tv-container">
            <video id="tv-video" muted></video>
            <div id="tv-spinner"></div>
            <div id="tv-play-button"><div id="tv-play-button-inner"></div></div>
            <div id="tv-controls">
              <button type="button" id="mute-button"></button>
              <input type="range" id="volume-bar" min="0" max="1" step="0.05" value="0">
              <button type="button" id="full-screen-button"></button>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-3 mt-3">
        <div class="list-group" id="channel-list">
          <button type="button" name="cbs" class="list-group-item list-group-item-action">
            KPIX (CBS)
          </button>
          <button type="button" name="nbc" class="list-group-item list-group-item-action">
            KNTV (NBC)
          </button>
          <button type="button" name="abc" class="list-group-item list-group-item-action">
            KGO (ABC)
          </button>
          <button type="button" name="fox" class="list-group-item list-group-item-action">
            KTVU (Fox)
          </button>
          <button type="button" name="pbs" class="list-group-item list-group-item-action">
            KQED (PBS)
          </button>
          <button type="button" name="cw" class="list-group-item list-group-item-action">
            KBCW (CW)
          </button>
        </div>
      </div>
    </div>

    <div class="row mt-3">
      <div class="col-md-9">
        <div class="alert alert-info" role="alert" id="unmute-message">
          Video is muted by default; <u id="unmute-here">unmute here</u></span>
          or use the player control bar.
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
      </div>
    </div>
    <hr>
    <div>
      <span>
        <img src="{% static 'puffer/dist/images/forum.svg' %}" class="icon">
        <a href="https://groups.google.com/forum/#!forum/puffer-stanford">Contact us</a>
      </span>
      |
      <span>
        <img src="{% static 'puffer/dist/images/star.svg' %}" class="icon">
        <a href="https://github.com/stanfordsnr/puffer">Star our repo</a></span>
      </span>
      |
      <span>
        <img src="{% static 'puffer/dist/images/wrench.svg' %}" class="icon">
        <a data-toggle="collapse" href="#debug-info"
           aria-expanded="false" aria-controls="debug-info">
          Debug info
        </a>
      </span>
      <div class="collapse py-2" id="debug-info">
        Video playback buffer (s): <span id="video-buf">N/A</span><br>
        Video resolution: <span id="video-res">N/A</span><br>
        Video encoding setting (CRF): <span id="video-crf">N/A</span><br>
        Video quality (SSIM dB): <span id="video-ssim">N/A</span><br>
        Video bitrate (kbps): <span id="video-bitrate">N/A</span>
      </div>
    </div>

  </div>

  <script src="{% static 'puffer/dist/js/jquery-3.3.1.slim.min.js' %}"></script>
  <script src="{% static 'puffer/dist/js/bootstrap.bundle.min.js' %}"></script>

  <script src="{% static 'puffer/js/player.js' %}"></script>
  {% if params_json %}
  <script type="text/javascript">
    init_player("{{ params_json|escapejs }}", "{{ csrf_token }}");
  </script>
  {% endif %}

  <script>
    gtag('event', 'conversion', {'send_to': 'AW-771906819/F7YICLutpZIBEIO6ifAC'});
    rdt('track', 'ViewContent');
  </script>
</body>

</html>

src/portal/puffer/templates/puffer/profile.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="{% static 'puffer/dist/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'puffer/css/common.css' %}">
  <title>Puffer</title>
  <link rel="icon" href="{% static 'puffer/dist/images/favicon.ico' %}">
</head>

<body>
  <!-- Navigation -->
  {% include "puffer/navigation.html" %}

  <!-- User Info -->
  <div class="container py-4">
    <p>Your username: {{ user.username }}</p>
    <p>
      Puffer uses an invitation token based system to allow users to invite other users.
      If you have any invitation tokens, they will show up below. Feel free to share them with
      friends who would also like to use Puffer.
    </p>
    <p><a href="{% url 'participate' %}">Have friends interested in Puffer?</a></p>

    {% if user.is_superuser %}
    <form class="form-inline" method="post" action="{% url 'profile' %}">
      {% csrf_token %}

      As an admin, you can generate an invitation token with
      <div class="form-group">
        <select type="text" class="form-control mx-2" name="addon-cnt" id="addon-cnt" required>
          <option>0</option>
          <option>1</option>
          <option>2</option>
          <option>3</option>
        </select>
        additional tokens:
      </div>
      <button type="submit" class="btn btn-primary ml-2">Generate a token</button>
    </form>
    {% endif %}

    {% if user.invitationtoken_set.all %}
    <br>
    <p>
      <strong>Total available invitation tokens:</strong>
      {{ user.invitationtoken_set.all.count }}
    </p>

    <div style="max-width:800px">
      <table class="table table-hover">
        <thead>
          <tr>
            <th scope="col" style="width:30%">Unshared tokens</th>
            <th scope="col" style="width:40%">Addtional tokens to generate</th>
            <th scope="col" style="width:30%">Once you share...</th>
          </tr>
        </thead>
        <tbody id="unshared-tokens">
        {% for t in user.invitationtoken_set.all %}
          {% if not t.shared %}
          <tr>
            <td class="text-monospace">{{ t.token }}</td>
            <td>{{ t.addon_cnt }}</td>
            <td>
              <span class="fake-link" onclick="share('{{ t.token }}', this, '{{ csrf_token }}')">
                mark shared
              </span>
            </td>
          </tr>
          {% endif %}
        {% endfor %}
        </tbody>
      </table>

      <table class="table table-hover" style="max-width: 800px">
        <thead>
          <tr>
            <th scope="col" style="width:30%">Shared tokens</th>
            <th scope="col" style="width:40%">Addtional tokens to generate</th>
            <th scope="col" style="width:30%">Click to unshare...</th>
          </tr>
        </thead>
        <tbody id="shared-tokens">
        {% for t in user.invitationtoken_set.all %}
          {% if t.shared %}
          <tr>
            <td class="text-monospace">{{ t.token }}</td>
            <td>{{ t.addon_cnt }}</td>
            <td>
              <span class="fake-link" onclick="unshare('{{ t.token }}', this, '{{ csrf_token }}')">
                mark unshared
              </span>
            </td>
          </tr>
          {% endif %}
        {% endfor %}
        </tbody>
      </table>
    </div>
    {% endif %}
  </div>

  <script src="{% static 'puffer/dist/js/jquery-3.3.1.slim.min.js' %}"></script>
  <script src="{% static 'puffer/dist/js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'puffer/js/profile.js' %}"></script>
</body>

</html>